### ISSUE TITLE
前端.md里描述回流、重绘有误

### ISSUE THREAD

**Issue by Evecang** [QZWQWQ/interview#1]
“当我们对 DOM的修改导致了样式的变化（color或background-color），却并未影响其几何属性时，浏览器不需重新计算元素的几何属性、直接为该元素绘制新的样式，这里就仅仅触发了回流” —— 这里仅仅触发的是重绘而不是回流

**Comment by QZWQWQ** [comment]
好，这个我近期调整下，还有一些在我本地的文档还没上传，我也整理下一并推上来吧

**Comment by Evecang** [comment]
> 
感谢
：）
